// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leyfwwmroijwnkrcblxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleWZ3d21yb2lqd25rcmNibHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MDA3NjcsImV4cCI6MjA4ODE3Njc2N30.3hqJf2jf625gizxVMFScafwf6-SStDblpsL4CYKY4FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});